django_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('api/', include('project.api.urls')),
]

project/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',  views.getRoutes),
    path('offers/', views.getOffers),
    path('offers/<str:pk>/', views.getOffer),
]

project/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutPage, name="logout"),
    path('register/', views.registerPage, name="register"),
    path('create-offer/', views.createofferPage, name="create-offer"),

    path('offer/<str:pk>/', views.offerPage, name="offer"),
    path('update-offer/<str:pk>/', views.updateOffer, name="update-offer"),
    path('delete-offer/<str:pk>/', views.deleteOffer, name="delete-offer"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

project/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

### Custom user model to login with email ###
class User(AbstractUser):
    username = models.CharField(max_length=200, null=True, unique=True)
    email = models.EmailField(unique=True, null=True)

    ### Change USERNAME_FIELD to 'username' instead of 'email' to avoid errors when creating super users with command manage.py createsuperuser ###
    ### Use 'email' to register/login with email
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


### This model will display property types ###
class LandType(models.Model):
    property_type = models.CharField(max_length=200)

    class Meta:
        ordering = ['-property_type']

    def __str__(self):
        return self.property_type


### These are the main fields to be used in FORMS when creating an offer. Note that not all have to be used ### 
class Offer(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    location = models.CharField(max_length=100)
    price = models.IntegerField(null=False)
    area = models.IntegerField(null=False)
    image = models.ImageField(null=True, default="farm-5836815_1920.jpg")
    created = models.DateTimeField(auto_now_add=True, null=True)
    views = models.IntegerField(default=0)
    property_type = models.ForeignKey(LandType, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['-views']

    def __str__(self):
        return self.name

project/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import User, Offer

##  Form to register user  ##
class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']


## Add the required fields to this Form from 'Offer' ##

class OfferForm(ModelForm):
    class Meta:
        model = Offer
        fields = ['name', 'description', 'location', 'price', 'area', 'property_type']

project/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from project.models import Offer
from .serializers import OfferSerializer
from project.api import serializers



##  Routes that display the all offers or specific offer data  ##
@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/offers',
        'GET /api/offers/:id'
    ]
    return Response(routes)


@api_view(['GET'])
def getOffers(request):
    offers = Offer.objects.all()
    serializer = OfferSerializer(offers, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getOffer(request, pk):
    offer = Offer.objects.get(id=pk)
    serializer = OfferSerializer(offer, many=False)
    return Response(serializer.data)

project/views.py
from django.db.models.fields import CharField
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .models import User, Offer, LandType
from .forms import UserRegisterForm, OfferForm



##  home page displaying offers  ##
def home(request):
    offers = Offer.objects.all()
    landtype = LandType.objects.all()
    context = {'offers': offers, 'landtype': landtype}
    return render(request, 'project/home.html', context)


##  login user  ##
def loginPage(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username OR password does not exist')

    context = {'page': page}
    return render(request, 'project/login_register.html', {'page':page})


##  logout user  ##
def logoutPage(request):
    logout(request)
    return redirect('home')


##  register user  ##
def registerPage(request):
    form = UserRegisterForm()

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'An error occurred during registration')

    return render(request, 'project/login_register.html', {'form': form})



##  Will display available offers  ##
def offerPage(request, pk):
    landtype = LandType.objects.all()
    offers = Offer.objects.get(id=pk)
    offers.views += 1
    offers.save()
    context = {'offer': offers, 'landtype':landtype}
    return render(request, 'project/offer.html', context)

## To prevent users from creating offers when not logged in. ##
@login_required(login_url='login')
def createofferPage(request):
    form = OfferForm()

    if request.method == 'POST':
        form = OfferForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')

    context = {'form': form}
    return render(request, 'project/create_offer.html', context)

## To prevent users from updating offers when not logged in, it also check to see if user is the host of the offer. Only host can update. ##
@login_required(login_url='login')
def updateOffer(request, pk):
    offer = Offer.objects.get(id=pk)
    form = OfferForm(instance=offer)
    if request.user != offer.host:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        offer.name = request.POST.get('name')
        offer.description = request.POST.get('description')
        offer.location = request.POST.get('location')
        offer.price = request.POST.get('price')
        offer.area = request.POST.get('area')
        offer.save()
        return redirect('home')

    context = {'form': form, 'offer': offer}
    return render(request, 'project/update_offer.html', context)

def propertyType(request):
    property_type = CharField(max_length=100)
    return render(request, 'project/property_types.html', {'property_type': property_type})


## To prevent users from deleting offers when not logged in, it also check to see if user is the host of the offer. Only host can delete. ##
@login_required(login_url='login')
def deleteOffer(request, pk):
    offer = Offer.objects.get(id=pk)

    if request.user != offer.host:
        return HttpResponse('Your are not allowed here!!')

    if request.method == 'POST':
        offer.delete()
        return redirect('home')
    return render(request, 'project/delete_offer.html', {'obj': offer})

project/templates/project/create_offer.html
{% extends 'main.html' %}
<h3>Create offer here..</h3>

{% block content %}
<hr>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
        <div class="container-lg bg-dark">
            <h2 class="text-center">Edit Offer</h2>
            <hr>
            <div class="row">
                <div class="offset-lg-4 col-4">
                    <div class="p-3 bg-dark text-light">
                        
                        <div>
                            <p>Name: {{form.name}}</p>
    
                            <p>Description: {{form.description}}</p>
                            <p>Location: {{form.location}}</p>
                            <p>Price: {{form.price}}</p>
                            <p>Area: {{form.area}}</p>
                            <p>Property Type: {{form.property_type}}</p>
                            <input type="submit" value="Create">
                        </div>
                        <hr>
                    </div>
                </div>
    
            </div>
        </div>
    </form>



<!-- <div>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        {{form.media}}
        <input type="submit" value="Create">
    </form>
</div> -->

{% endblock %}

project/templates/project/delete_offer.html
{% extends 'main.html' %}

{% block content %}

<form class="form" action="" method="POST">
{% csrf_token %}
    <div class="container-lg bg-secondary">
        <h2 class="text-center">Delete Offer</h2>
        <hr>
        <div class="row">
            <div class="col">
                <div class="p-3 bg-success text-light">
                    
                    <div>
                        <p>Are you sure you want to delete offer named: <b>{{obj}}?</b></p>
                        <input type="submit" value="Confirm">
                    </div>
                    <hr>
                    
                </div>
            </div>

        </div>
    </div>
</form>


{% endblock %}

project/templates/project/home.html
{% extends 'main.html' %}

{% block content %}

<div class="container-lg bg-dark">
    <hr>
    <div class="row">
        <div class="col">
            <h2 class="text-center text-light">Most Viewed</h2>
            <div class="p-5 text-light">
                {% for offer in offers %}
                <div>
            
                    <a href="{% url 'offer' offer.id %}">
                        <h5>#{{offer.id}} - {{offer.name}}</h5>
                    </a>
                    <small>Views: {{offer.views}}, Location: {{offer.location}}</small>
                </div>
                <hr>   
                {% endfor %}
                <hr>
            </div>
            <h2 class="text-center text-light">Popular Land</h2>
            <div class="p-5 bg-new text-light">
                {% for land in landtype %}
                <div>
                    <small>{{land.property_type}}</small>
                    <p>{{land.offer_set.all.count}}</p>
                </div>
                {% endfor %}
                <hr>
            </div>
        </div>

        <div class="col-9">
            <h3 class="text-center text-light">Land for Sale</h3>
            <div class="p-3 text-light">
                {% for offer in offers %}
                <div class="container">
                    <img class="img-thumbnail" src="images/farm.jpg">
                    <div class="text-center">
                        <a href="{% url 'offer' offer.id %}"><h4>{{offer.id}} -- {{offer.name}}</h4></a>
                        <b>$ {{offer.price}}</b>
                        <br>
                        <small>Views: {{offer.views}}</small>
                    </div>
                </div>
                <hr>
                {% endfor %}
            </div>
            {% if request.user.is_authenticated %}
            <div class="text-light">
                <h3>Logged in as: {{request.user.username}}</h3>
            {% else %}
                <h3>Not logged in.</h3>
            {%  endif %}
            </div>
        </div>

    </div>
</div>


{% endblock %}

project/templates/project/login_register.html
{% extends 'main.html' %}

{% block content %}

{% if page == 'login' %}
<hr>
<div class="text-center text-light">
    <form method="POST" action="">
        {% csrf_token %}

        <label>Username:</label>
        <input type="text" name="email" placeholder="Enter Username" />

        <label>Password:</label>
        <input type="password" name="password" placeholder="Enter Password" />

        <input type="submit" value="Login" />
    </form>
    <br>
    <p>Havent signed up yet?</p>
    <a href="{% url 'register' %}">Sign up</a>
</div>
{% else %}
<hr>
<div class="offset-lg-4 col-4 text-light">
    <h3 class="text-center">Register below!</h3>
    <hr><br>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register" />
    </form>
    <p>Already signed up yet?</p>
    <a href="{% url 'login' %}">Login</a>
</div>
{% endif %}
{% endblock content %}

project/templates/project/offer.html
{% extends 'main.html' %}

{% block content %}

{<div class="container-lg bg-dark">
    <div class="row">
        <div class="col">
            
            <h2 class="text-center text-light">Popular Land</h2>
            <div class="p-5 text-light">
                {% for land in landtype %}
                <div>
                    <small>{{land.property_type}}</small>
                    <p>{{land.offer_set.all.count}}</p>
                </div>
                {% endfor %}
                <hr>
            </div>
        </div>
        <div class="col-9">
            <h2 class="text-center text-light">Showcase Properties</h2>
            <div class="p-3 text-light">
                <div class="container">
                    <h5>Name: {{offer.name}}</h5>
                    
                    <h5>Description: {{offer.description}}</h5>
                    <h5>Location: {{offer.location}}</h5>
                    <h5>Price: {{offer.price}} $</h5>
                    <h5>Area: {{offer.area}} acres</h5>
                    {% if offer.host == request.user %}
                    <a href="{% url 'update-offer' offer.id %}">Edit</a>
                    <a href="{% url 'delete-offer' offer.id %}">Delete</a>
                    {% endif %}
                </div>
                <hr>
            </div>
        </div>
    </div>
</div>}


{% endblock %}

project/templates/project/update_offer.html
{% extends 'main.html' %}

{% block content %}

<hr>
<form class="form" action="" method="POST">
{% csrf_token %}
    <div class="container-lg bg-dark">
        <h2 class="text-center">Edit Offer</h2>
        <hr>
        <div class="row">
            <div class="offset-lg-4 col-4">
                <div class="p-3 bg-dark text-light">
                    
                    <div>
                        <p>Name: {{form.name}}</p>

                        <p>Description: {{form.description}}</p>
                        <p>Location: {{form.location}}</p>
                        <p>Price: {{form.price}}</p>
                        <p>Area: {{form.area}}</p>
                        <input type="submit" value="Update">
                    </div>
                    <hr>
                </div>
            </div>

        </div>
    </div>
</form>


{% endblock %}

templates/api_example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API EXAMPLE</title>
</head>
<body>
    
    <h2>API</h2>

<script>

    let getOffers = async () => {
        let response = await fetch('http://127.0.0.1:8000/api/offers/')
        console.log('FOUND: ', response)
    }

    getOffers()

</script>
</body>
</html>

templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <title>Properties</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    <form method="GET" action="{% url 'home' %}">
    </form>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav ms-auto">
        {% if request.user.is_authenticated %}
        <a class="nav-link" href="{% url 'logout' %}">
            <p>Logout</p>
        </a>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create-offer' %}">Create Offer</a>
        </li>
        {% else %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
          {% endif %}
      </ul>
    </div>
</nav>